ip: localhost
server:
  port: 8080
spring:
  redis:
    host: 47.113.178.187          # Redis服务器主机地址
    port: 6379               # Redis服务器端口
    password: 123              # Redis服务器密码（如果有的话）
    database: 0              # Redis数据库索引，默认是0ct
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20         # 连接池最大连接数
        max-idle: 5           # 连接池中最大空闲连接数
        min-idle: 0           # 连接池中最小空闲连接数
        max-wait: -1          # 最大等待时间（负数表示无限）

  application:
    #????????
    name: new_piggery
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${ip}:3306/piggery?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: rootroot
servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB
mybatis-plus:
  configuration:
    #???????????????????????????????????????????id_Number????????idNumber??
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#???????ID
# global-config:
 #   db-config:
  #    id-type: ASSIGN_ID

